//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uyg04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string kayitId { get; set; }
        public string kayitSoruId { get; set; }
        public string kayitDersId { get; set; }
        public string kayitOgrId { get; set; }
        public string kayitCevapId { get; set; }

        public virtual Ders Ders { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
        public virtual Soru Soru { get; set; }
        public virtual Cevap Cevap { get; set; }
    }
}
